#
# Slideshow reverse proxy
#
# Frontend implementations (React, Vue, Angular, etc.) expose the
# "frontend" network alias.
#
# Backend implementations (NestJS, Django, Symfony, Laravel, etc.)
# expose the "api" network alias.
#
# Using variables for proxy_pass causes nginx to resolve hostnames at
# request time instead of startup, allowing the proxy to run even when
# only a frontend or only a backend profile is active.
#
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    server_name localhost;

    # Docker DNS
    resolver 127.0.0.11 valid=5s ipv6=off;

    # Logistical upstreams
    set $api http://api:8000;
    set $frontend http://frontend:5173;

    # Configurables
    client_max_body_size 50m;

    # ----------------------------------------------------------------------------
    # Frontend
    # ----------------------------------------------------------------------------

    location / {
        proxy_pass $frontend;

        proxy_http_version 1.1;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;

        # Support hot module replacement (React/Vue)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

    # ----------------------------------------------------------------------------
    # API
    # ----------------------------------------------------------------------------

    location ~ ^/api(?<path>/.*)?$ {
        proxy_pass $api$path$is_args$args;

        proxy_http_version 1.1;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;

        # Support hot module replacement (GraphQL/WebSockets)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}