services:
  nest:
    build:
      target: test-cov
    env_file:
      - ../../backends/nest/.env.test
    volumes:
      - ../../backends/nest/logs:/app/logs:Z
      - ../../backends/nest/coverage:/app/coverage:Z

  postgres:
    env_file:
      - ../config/postgres.test.env
    tmpfs:
      - /var/lib/postgresql/data