services:
  nest:
    build:
      target: test-cov
    env_file:
      - ../../backends/nest/.env.test

  postgres:
    env_file:
      - ../config/postgres.test.env
    tmpfs:
      - /var/lib/postgresql/data